#ifndef MCAL_EXTERNAL_INTERRUPT_DRIVER_EXE_INTERRUPT_CONFIG_H_
#define MCAL_EXTERNAL_INTERRUPT_DRIVER_EXE_INTERRUPT_CONFIG_H_

#define EXE_INTERRUPT_0 {PORT_D,PIN_2}
#define EXE_INTERRUPT_1 {PORT_D,PIN_3}
#define EXE_INTERRUPT_2 {PORT_C,PIN_2}

#endif
