#ifndef EXE_INTERRUPT_CONFIG_H_
#define EXE_INTERRUPT_CONFIG_H_

#define EXE_INTERRUPT_0 {PORT_D, PIN_2} // INT0 on PD2
#define EXE_INTERRUPT_1 {PORT_D, PIN_3} // INT1 on PD3

#endif /* MCAL_EXTERNAL_INTERRUPT_DRIVER_EXE_INTERRUPT_CONFIG_H_ */