
#include <util/delay.h>
#include "ULTRASONIC-HANDLER/ultrasonic_int.h"
#include "ULTRASONIC-HANDLER/ultrasonic_cfg.h"
#include "DIO-DRIVER/dio_int.h"
#include "ICU-HANDLER/ICU_int.h"
uint8_t g_edgeCount = (INITIAL_VALUE_ZERO);
uint16_t g_T_edge = (INITIAL_VALUE_ZERO);

void Ultrasonic_init(ultrasonic_config_t *ultrasonic_config)
{
    ICU_Init();

    ICU_SetCallback(Ultrasonic_edgeProcessing);

    DIO_u8SetPinMode(ultrasonic_config->trigger.port, ultrasonic_config->trigger.port, OUTPUT);
}

void Ultrasonic_Trigger(ultrasonic_config_t *ultrasonic_config)
{
    DIO_u8SetPinValue(ultrasonic_config->trigger.port, ultrasonic_config->trigger.pin, HIGH);
    _delay_us(TRIGGER_DELAY);
    DIO_u8SetPinValue(ultrasonic_config->trigger.port, ultrasonic_config->trigger.pin, LOW);
}

uint16_t Ultrasonic_readDistance(ultrasonic_config_t *ultrasonic_config)
{

    Ultrasonic_Trigger(ultrasonic_config);

    float32_t _scale = (float32_t)(((2) * (F_CPU)) / ((SPEED_OF_SOUND) * (F_PRESCALER)));

    /*
     *  speed in cm/us
     */
    uint16_t distance = (uint16_t)((g_T_edge) / (_scale));

    return (distance);
}

/*
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
    (++g_edgeCount);

    switch (g_edgeCount)
    {
    case 1:
        ICU_ClearTimer();
        ICU_SetEdgeDetection(ICU_EDGE_FALLING);
        break;
    case 2:
        g_T_edge = ICU_GetCaptureValue();
        ICU_ClearTimer();
        ICU_SetEdgeDetection(ICU_EDGE_RISING);
        g_edgeCount = (INITIAL_VALUE_ZERO);
        break;
    }
}