
#include <util/delay.h>
#include "ULTRASONIC-HANDLER/ultrasonic_int.h"
#include "ULTRASONIC-HANDLER/ultrasonic_cfg.h"
#include "DIO-DRIVER/dio_int.h"

uint8_t g_edgeCount = (INITIAL_VALUE_ZERO);
uint16_t g_T_edge = (INITIAL_VALUE_ZERO);

ICU_ConfigType ICU_conf = {
    F_CPU_8,
    RAISING};

void Ultrasonic_init(void)
{
    ICU_init(&ICU_conf);

    ICU_setCallBack(Ultrasonic_edgeProcessing);

    DIO_u8SetPinMode(Ultrasonic_TRIGGER_PORT, Ultrasonic_TRIGGER_PIN, OUTPUT);
}

void Ultrasonic_Trigger(void)
{
    DIO_u8SetPinValue(Ultrasonic_TRIGGER_PORT, Ultrasonic_TRIGGER_PIN, HIGH);
    _delay_us(TRIGGER_DELAY);
    DIO_u8SetPinValue(Ultrasonic_TRIGGER_PORT, Ultrasonic_TRIGGER_PIN, LOW);
}

uint16_t Ultrasonic_readDistance(void)
{

    Ultrasonic_Trigger();

    float32_t _scale = (float32_t)(((2) * (F_CPU)) / ((SPEED_OF_SOUND) * (F_PRESCALER)));

    /*
     *  speed in cm/us
     */
    uint16_t distance = (uint16_t)((g_T_edge) / (_scale));

    return (distance);
}

/*
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
    (++g_edgeCount);

    switch (g_edgeCount)
    {
    case 1:
        ICU_clearTimerValue();
        ICU_setEdgeDetectionType(FALLING);
        break;
    case 2:
        g_T_edge = ICU_getInputCaptureValue();
        ICU_clearTimerValue();
        ICU_setEdgeDetectionType(RAISING);
        g_edgeCount = (INITIAL_VALUE_ZERO);
        break;
    }
}