#ifndef USART_CONFIGURATION_H_
#define USART_CONFIGURATION_H_

#include "CPU_Configuration.h"

typedef enum
{
	USART_CHAR_SIZE_5 = 0b000,
	USART_CHAR_SIZE_6 = 0b001,
	USART_CHAR_SIZE_7 = 0b010,
	USART_CHAR_SIZE_8 = 0b011,
	USART_CHAR_SIZE_9 = 0b111
} USART_CharSize_t;

typedef enum
{
	USART_PARITY_NONE = 0b00,
	USART_PARITY_EVEN = 0b10,
	USART_PARITY_ODD = 0b11
} USART_Parity_t;

typedef enum
{
	USART_STOP_1 = 0,
	USART_STOP_2 = 1
} USART_StopBits_t;

#define USART_DEFAULT_BAUD_RATE 9600
#define USART_DEFAULT_CHAR_SIZE USART_CHAR_SIZE_8
#define USART_DEFAULT_PARITY USART_PARITY_NONE
#define USART_DEFAULT_STOP_BITS USART_STOP_1
#define USART_DEFAULT_U2X 0

#endif
